name: Frontend Build and Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

on:
  push:
    branches: [main, develop]
    tags: ['v*']
    paths:
      - 'apps/frontend/**'
      - 'terraform/modules/frontend/**'
      - '.github/workflows/frontend-deploy.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

env:
  AWS_REGION: us-west-2
  TF_VERSION: 1.5.0

jobs:
  # Determine environment
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set-env.outputs.env_name }}
    steps:
      - id: set-env
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "env_name=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/v* ]]; then
            echo "env_name=prod" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            echo "env_name=staging" >> $GITHUB_OUTPUT
          else
            echo "env_name=dev" >> $GITHUB_OUTPUT
          fi

  # Call shared workflow to generate terraform variables
  terraform-vars:
    needs: set-environment
    uses: ./.github/workflows/terraform-vars.yml
    with:
      environment: ${{ needs.set-environment.outputs.env_name }}
    secrets: inherit

  # Build and deploy frontend
  build:
    runs-on: ubuntu-latest
    needs: set-environment
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
          cache-dependency-path: 'apps/frontend/pnpm-lock.yaml'

      - name: Install dependencies
        run: |
          cd apps/frontend
          pnpm install

      - name: Build frontend
        run: |
          cd apps/frontend
          pnpm run build

      - name: Debug - List build directory contents
        run: |
          echo "Checking for build output directory..."
          ls -la apps/frontend/
          echo "Checking 'dist' directory (Vite default)..."
          ls -la apps/frontend/dist/ || echo "dist directory not found"
          echo "Checking 'public' directory..."
          ls -la apps/frontend/public/ || echo "public directory not found"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload build artifacts
        run: |
          aws s3 sync apps/frontend/dist/ s3://swashflag-${{ needs.set-environment.outputs.env_name }}-frontend/ --delete

      - name: Invalidate CloudFront cache
        if: needs.set-environment.outputs.env_name == 'prod' || needs.set-environment.outputs.env_name == 'staging'
        run: |
          DISTRIBUTION_ID=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          if [ -n "$DISTRIBUTION_ID" ]; then
            echo "Creating CloudFront invalidation for distribution $DISTRIBUTION_ID"
            aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
          else
            echo "No CloudFront distribution found with matching origin pattern"
            echo "Listing all distributions for debugging:"
            aws cloudfront list-distributions --query "DistributionList.Items[*].{Id:Id,Origins:Origins.Items[*].DomainName}" --output json
            # Don't fail the build
            exit 0
          fi

  # Deploy infrastructure with Terraform
  terraform:
    needs: [build, terraform-vars, set-environment]
    runs-on: ubuntu-latest
    if: needs.terraform-vars.outputs.terraform_vars_set == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download terraform.tfvars
        uses: actions/download-artifact@v4
        with:
          name: terraform-vars-${{ needs.set-environment.outputs.env_name }}
          path: terraform/environments/${{ needs.set-environment.outputs.env_name }}

      - name: Terraform Init
        run: |
          cd terraform/environments/${{ needs.set-environment.outputs.env_name }}
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform/environments/${{ needs.set-environment.outputs.env_name }}
          terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          cd terraform/environments/${{ needs.set-environment.outputs.env_name }}
          terraform apply -auto-approve tfplan